tap "golangci/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Cross-platform make
brew "cmake"
# Lightweight, framework-agnostic database migration tool
brew "dbmate"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Interpreted, interactive, object-oriented programming language
brew "python@3.8", link: false
# Isolated development environments using Docker
brew "docker-compose"
# Create Docker hosts locally and on cloud providers
brew "docker-machine"
# Modern replacement for 'ls'
brew "exa"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Postgres C API library
brew "libpq", link: true
# Package manager for the Lua programming language
brew "luarocks"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Manage compile and link flags for libraries
brew "pkg-config"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Fast linters runner for Go.
brew "golangci/tap/golangci-lint"
cask "alacritty"
cask "alfred"
cask "docker"
cask "firefox"
cask "font-hack"
cask "google-chrome"
cask "karabiner-elements"
